run:
  timeout: 10m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
  disable:
    - unused  # Can be slow on large codebases

linters-settings:
  errcheck:
    check-blank: false  # Allow blank assignments for explicitly ignored errors
  govet:
    enable:
      - shadow  # Check for variable shadowing

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
  max-issues-per-linter: 0
  max-same-issues: 0